/**
 * \file Cpu0_Main.h
 * \brief System initialization and main program implementation.
 *
 * \version iLLD_Demos_1_0_1_11_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 * \defgroup IfxLld_Demo_STMDemo_SrcDoc Source code documentation
 * \ingroup IfxLld_Demo_STMDemo
 *
 */

#ifndef CPU0_MAIN_H
#define CPU0_MAIN_H

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/


#include "Cpu/Std/Ifx_Types.h"
/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Type Definitions------------------------------*/
/******************************************************************************/

typedef struct
{
    float32 sysFreq;                /**< \brief Actual SPB frequency */
    float32 cpuFreq;                /**< \brief Actual CPU frequency */
    float32 pllFreq;                /**< \brief Actual PLL frequency */
    float32 stmFreq;                /**< \brief Actual STM frequency */
} AppInfo;

/** \brief Application information */
typedef struct
{
    AppInfo info;                               /**< \brief Info object */
} App_Cpu0;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

IFX_EXTERN App_Cpu0 g_AppCpu0;
/*电感PD*/
extern float Elec_P;       extern float Elec_D;         extern float Elec_cor;
/*电感备用选项*/
extern float Elec_I;       extern float Elec_pLimit;
/*电感PD限幅*/
extern float Elec_coLimit;
/*电机1PID*/
extern float Motor_1P;       extern float Motor_1I;       extern float Motor_1D;     extern float Motor_1Target;
extern float Motor_1cor;     extern float Motor_1Puse;
/*电机2PID*/
extern float Motor_2P;       extern float Motor_2I;       extern float Motor_2D;     extern float Motor_2Target;
extern float Motor_2cor;     extern float Motor_2Puse;
/*电机限幅*/
extern float Motor_pLimit;   extern float Motor_coLimit;
extern uint8 Elec_pidStatus;    extern uint8 Motor_pidStatus;
extern float Elec_coLimit;
extern float Speed;            extern float Speed_set;
extern float Motor_1Pcor;      extern float Motor_1Icor;       extern float Motor_1Dcor;
extern float Motor_2Pcor;      extern float Motor_2Icor;       extern float Motor_2Dcor;
extern float Elec_A;    extern float Elec_B;    extern float Elec_C;



//-----------------------------
extern double H[3][3] ;
extern int picturetime;
//-----------------------------
//摄像头PID(左边线找到的中线)
extern float Camera_leftP;     extern float Camera_leftI;     extern float Camera_leftD;   extern float Camera_leftCor;
//摄像头PID(右边线找到的中线)
extern float Camera_rightP;     extern float Camera_rightI;     extern float Camera_rightD;  extern float Camera_rightCor;
//摄像头PID(（左+右）/2)
//extern float Camera_midP;     extern float Camera_midI ;     extern float Camera_midD ;   extern float Camera_midCor;
//------------------------------
//摄像头PD限幅(左边线找到的中线)
extern float Camera_leftPLimit;    extern float Camera_leftCoLimit;   extern float Camera_leftBoost;
//摄像头PD限幅(右边线找到的中线)
extern float Camera_rightPLimit;    extern float Camera_rightCoLimit;   extern float Camera_rightBoost;
//
//extern float Camera_midPLimit;    extern float Camera_midCoLimit;   extern float Camera_midBoost;

extern float Speed_accVar; extern uint8 Barrier_Judege_Status;

//------------------------------图像------------------------------
extern uint8 inv_map_x[120][188];
extern uint8 inv_map_y[120][188];
extern uint8 Isr_FinishFlat_CCU60_CH0; //中断CCU60_CH0中断完成表示位
extern uint8 Isr_sendDataCnt;

#endif
